import '../../Features/OverTime/DomainLayer/Entities/course_entity.dart';

List<CourseEntity> dummyCourseList = [
  CourseEntity(
    courseID: 101,
    instituteID: 1,
    subjectID: 101,
    studentID: 1001,
    sessionID: 1,
    startDate: DateTime(2023, 8, 21),
    endDate: DateTime(2023, 12, 21),
    courseType: "online",
    hourlyRate: 25.0,
    studentName: "Alice Smith",
    studentNote: "Has previous programming experience.",
    courseDuration: 30.0,
    total: 750.0,
    active: false,
  ),
  CourseEntity(
      courseID: 102,
      instituteID: 2,
      subjectID: 102,
      studentID: 1002,
      sessionID: 2,
      startDate: DateTime(2023, 9, 5),
      endDate: DateTime(2023, 11, 25),
      courseType: "offline",
      hourlyRate: 30.0,
      studentName: "Bob Johnson",
      studentNote: "Needs extra focus on data analysis.",
      courseDuration: 45.0,
      total: 1350.0,
      active: true),
  CourseEntity(
      courseID: 104,
      instituteID: 1,
      subjectID: 103,
      studentID: 1003,
      sessionID: 1,
      startDate: DateTime(2023, 10, 15),
      endDate: DateTime(2024, 1, 15),
      courseType: "online",
      hourlyRate: 20.0,
      studentName: "Eve Williams",
      courseDuration: 40.0,
      total: 800.0,
      active: true),
  CourseEntity(
      courseID: 101,
      instituteID: 1,
      subjectID: 101,
      studentID: 1001,
      sessionID: 1,
      startDate: DateTime(2023, 8, 21),
      endDate: DateTime(2023, 12, 21),
      courseType: "online",
      hourlyRate: 25.0,
      studentName: "Alice Smith",
      studentNote: "Has previous programming experience.",
      courseDuration: 30.0,
      total: 750.0,
      active: true),

  CourseEntity(
      courseID: 101,
      instituteID: 1,
      subjectID: 101,
      studentID: 1001,
      sessionID: 1,
      startDate: DateTime(2023, 8, 21),
      endDate: DateTime(2023, 12, 21),
      courseType: "online",
      hourlyRate: 25.0,
      studentName: "Alice Smith",
      studentNote: "Has previous programming experience.",
      courseDuration: 30.0,
      total: 750.0,
      active: false),
  CourseEntity(
      courseID: 101,
      instituteID: 1,
      subjectID: 101,
      studentID: 1001,
      sessionID: 1,
      startDate: DateTime(2023, 8, 21),
      endDate: DateTime(2023, 12, 21),
      courseType: "online",
      hourlyRate: 25.0,
      studentName: "Alice Smith",
      studentNote: "Has previous programming experience.",
      courseDuration: 30.0,
      total: 750.0,
      active: true),
  CourseEntity(
      courseID: 101,
      instituteID: 1,
      subjectID: 101,
      studentID: 1001,
      sessionID: 1,
      startDate: DateTime(2023, 8, 21),
      endDate: DateTime(2023, 12, 21),
      courseType: "online",
      hourlyRate: 25.0,
      studentName: "Alice Smith",
      studentNote: "Has previous programming experience.",
      courseDuration: 30.0,
      total: 750.0,
      active: true),
  CourseEntity(
      courseID: 101,
      instituteID: 1,
      subjectID: 101,
      studentID: 1001,
      sessionID: 1,
      startDate: DateTime(2023, 8, 21),
      endDate: DateTime(2023, 12, 21),
      courseType: "online",
      hourlyRate: 25.0,
      studentName: "Alice Smith",
      studentNote: "Has previous programming experience.",
      courseDuration: 30.0,
      total: 750.0,
      active: true),
  CourseEntity(
      courseID: 101,
      instituteID: 1,
      subjectID: 101,
      studentID: 1001,
      sessionID: 1,
      startDate: DateTime(2023, 8, 21),
      endDate: DateTime(2023, 12, 21),
      courseType: "online",
      hourlyRate: 25.0,
      studentName: "Alice Smith",
      studentNote: "Has previous programming experience.",
      courseDuration: 30.0,
      total: 750.0,
      active: true),
  CourseEntity(
      courseID: 101,
      instituteID: 1,
      subjectID: 101,
      studentID: 1001,
      sessionID: 1,
      startDate: DateTime(2023, 8, 21),
      endDate: DateTime(2023, 12, 21),
      courseType: "online",
      hourlyRate: 25.0,
      studentName: "Alice Smith",
      studentNote: "Has previous programming experience.",
      courseDuration: 30.0,
      total: 750.0,
      active: false),
  CourseEntity(
      courseID: 101,
      instituteID: 1,
      subjectID: 101,
      studentID: 1001,
      sessionID: 1,
      startDate: DateTime(2023, 8, 21),
      endDate: DateTime(2023, 12, 21),
      courseType: "online",
      hourlyRate: 25.0,
      studentName: "Alice Smith",
      studentNote: "Has previous programming experience.",
      courseDuration: 30.0,
      total: 750.0,
      active: false),
  CourseEntity(
      courseID: 101,
      instituteID: 1,
      subjectID: 101,
      studentID: 1001,
      sessionID: 1,
      startDate: DateTime(2023, 8, 21),
      endDate: DateTime(2023, 12, 21),
      courseType: "online",
      hourlyRate: 25.0,
      studentName: "Alice Smith",
      studentNote: "Has previous programming experience.",
      courseDuration: 30.0,
      total: 750.0,
      active: false),
  // Add more courses as needed
];
